import type { CollectionConfig } from 'payload'

import { adminEditorOrSelf, adminOrEditor, anyone } from '../access'
import { slugField } from '../fields/slug'

export const Members: CollectionConfig = {
  slug: 'members',
  admin: {
    useAsTitle: 'name',
    group: 'People',
    defaultColumns: ['name', 'role', 'orcid'],
  },
  access: {
    read: anyone,
    create: adminOrEditor,
    // A group member edits their own profile (linked via the user field)
    update: adminEditorOrSelf,
    delete: adminOrEditor,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
    slugField('name'),
    {
      name: 'user',
      type: 'relationship',
      relationTo: 'users',
      unique: true,
      admin: {
        position: 'sidebar',
        description: 'Account for profile self-editing',
      },
      access: {
        update: ({ req: { user } }) => user?.role === 'admin' || user?.role === 'editor',
      },
    },
    {
      name: 'role',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Faculty', value: 'faculty' },
        { label: 'Researcher', value: 'researcher' },
        { label: 'PhD student', value: 'phd' },
        { label: 'MSc student', value: 'msc' },
        { label: 'Alumni', value: 'alumni' },
      ],
    },
    {
      name: 'photo',
      type: 'upload',
      relationTo: 'media',
    },
    {
      name: 'bio',
      type: 'richText',
    },
    {
      name: 'bioAiDraft',
      type: 'textarea',
      admin: {
        description:
          'AI bio draft. Generated by the pipeline; the profile owner moves what they want into bio.',
      },
    },
    {
      name: 'researchInterests',
      type: 'text',
      hasMany: true,
    },
    {
      type: 'row',
      fields: [
        { name: 'orcid', type: 'text', admin: { width: '33%' } },
        { name: 'openalexId', type: 'text', admin: { width: '33%' } },
        { name: 'dblpKey', type: 'text', admin: { width: '33%' } },
      ],
    },
    {
      name: 'links',
      type: 'group',
      fields: [
        {
          name: 'linkedin',
          type: 'text',
          admin: { description: 'LinkedIn or Técnico page — required by the brief' },
        },
        { name: 'tecnicoPage', type: 'text' },
        { name: 'personalPage', type: 'text' },
        { name: 'googleScholar', type: 'text' },
        { name: 'github', type: 'text' },
      ],
    },
    {
      name: 'email',
      type: 'email',
    },
    {
      name: 'showEmail',
      type: 'checkbox',
      defaultValue: false,
      admin: { description: 'Show the email on the site (owner opt-in)' },
    },
    {
      name: 'careerTrajectory',
      type: 'textarea',
      admin: {
        description: 'Career trajectory (for alumni)',
        condition: (data) => data?.role === 'alumni',
      },
    },
  ],
}
