import type { CollectionConfig } from 'payload'

import { adminEditorOrSelf, adminOrEditor, anyone } from '../access'
import { slugField } from '../fields/slug'

export const Members: CollectionConfig = {
  slug: 'members',
  admin: {
    useAsTitle: 'name',
    group: 'People',
    defaultColumns: ['name', 'role', 'membershipStatus', 'orcid', 'cienciaId'],
  },
  access: {
    read: anyone,
    create: adminOrEditor,
    // A group member edits their own profile (linked via the user field)
    update: adminEditorOrSelf,
    delete: adminOrEditor,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
    slugField('name'),
    {
      name: 'user',
      type: 'relationship',
      relationTo: 'users',
      unique: true,
      admin: {
        position: 'sidebar',
        description: 'Account for profile self-editing',
      },
      access: {
        update: ({ req: { user } }) => user?.role === 'admin' || user?.role === 'editor',
      },
    },
    {
      name: 'role',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Faculty', value: 'faculty' },
        { label: 'Researcher', value: 'researcher' },
        { label: 'PhD student', value: 'phd' },
        { label: 'MSc student', value: 'msc' },
      ],
    },
    {
      name: 'membershipStatus',
      type: 'select',
      required: true,
      defaultValue: 'active',
      index: true,
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Completed', value: 'completed' },
      ],
      admin: {
        description: 'Current relationship with the MLKD group or project.',
      },
    },
    {
      name: 'photo',
      type: 'upload',
      relationTo: 'media',
    },
    {
      // Most profiles here show initials because a photo has to be found, cropped
      // and uploaded by hand. This button asks the member's own LinkedIn account
      // for it instead — one click, with their consent (Sign In with LinkedIn).
      name: 'linkedinImport',
      type: 'ui',
      admin: {
        components: { Field: '/components/admin/ConnectLinkedInButton#ConnectLinkedInButton' },
      },
    },
    {
      name: 'bio',
      type: 'richText',
    },
    {
      name: 'bioAiDraft',
      type: 'textarea',
      admin: {
        description:
          'AI bio draft. Generated by the pipeline; the profile owner moves what they want into bio.',
      },
    },
    {
      name: 'researchInterests',
      type: 'text',
      hasMany: true,
    },
    {
      type: 'row',
      fields: [
        { name: 'orcid', type: 'text', unique: true, index: true, admin: { width: '20%' } },
        { name: 'cienciaId', type: 'text', unique: true, index: true, admin: { width: '20%' } },
        { name: 'openalexId', type: 'text', unique: true, index: true, admin: { width: '20%' } },
        { name: 'dblpKey', type: 'text', unique: true, index: true, admin: { width: '20%' } },
        { name: 'tecnicoId', type: 'text', unique: true, index: true, admin: { width: '20%' } },
      ],
    },
    {
      // Baseline for the "what did the platform actually add?" question: how many
      // papers this person was known to have BEFORE OpenAlex ingest (old site, CV,
      // their own list). The coverage report compares it against the linked
      // publications on the site to show the discovered difference. Left empty it
      // simply drops out of that report — we never invent a baseline.
      name: 'knownPublicationCount',
      type: 'number',
      min: 0,
      admin: {
        description:
          'Publications known before the platform imported from OpenAlex (old site / CV). Used by the coverage report to show how many extra papers were discovered. Leave empty if unknown.',
      },
    },
    {
      name: 'links',
      type: 'group',
      fields: [
        {
          name: 'linkedin',
          type: 'text',
          admin: { description: 'LinkedIn or Técnico page — required by the brief' },
        },
        { name: 'tecnicoPage', type: 'text' },
        { name: 'personalPage', type: 'text' },
        { name: 'googleScholar', type: 'text' },
        { name: 'github', type: 'text' },
      ],
    },
    {
      name: 'email',
      type: 'email',
    },
    {
      name: 'showEmail',
      type: 'checkbox',
      defaultValue: false,
      admin: { description: 'Show the email on the site.' },
    },
    {
      type: 'row',
      fields: [
        {
          name: 'showLinkedIn',
          type: 'checkbox',
          defaultValue: true,
          admin: { width: '33%', description: 'Show LinkedIn on the public profile.' },
        },
        {
          name: 'showGitHub',
          type: 'checkbox',
          defaultValue: true,
          admin: { width: '33%', description: 'Show GitHub on the public profile.' },
        },
        {
          name: 'showORCID',
          type: 'checkbox',
          defaultValue: true,
          admin: { width: '33%', description: 'Show ORCID on the public profile.' },
        },
      ],
    },
    {
      type: 'row',
      fields: [
        {
          name: 'showCienciaId',
          type: 'checkbox',
          defaultValue: true,
          admin: { width: '33%', description: 'Show Ciência Vitae on the public profile.' },
        },
        {
          name: 'showDBLP',
          type: 'checkbox',
          defaultValue: true,
          admin: { width: '33%', description: 'Show DBLP on the public profile.' },
        },
        {
          name: 'showTecnicoPage',
          type: 'checkbox',
          defaultValue: true,
          admin: { width: '33%', description: 'Show Técnico page when explicitly stored.' },
        },
      ],
    },
    {
      type: 'row',
      fields: [
        {
          name: 'showPersonalPage',
          type: 'checkbox',
          defaultValue: true,
          admin: { width: '50%', description: 'Show personal website on the public profile.' },
        },
        {
          name: 'showGoogleScholar',
          type: 'checkbox',
          defaultValue: true,
          admin: { width: '50%', description: 'Show Google Scholar on the public profile.' },
        },
      ],
    },
    {
      name: 'contactsSource',
      type: 'text',
      admin: {
        description: 'Internal provenance for imported contact data. Not rendered publicly.',
      },
    },
    {
      name: 'contactsVerifiedAt',
      type: 'date',
      admin: {
        description: 'When contact data was imported or last reviewed.',
      },
    },
    {
      name: 'needsContactReview',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        description: 'Contact information is missing or needs manual confirmation.',
      },
    },
    {
      type: 'row',
      fields: [
        {
          name: 'identifiersVerified',
          type: 'checkbox',
          defaultValue: false,
          admin: { width: '25%' },
        },
        {
          name: 'identifiersConfidence',
          type: 'select',
          options: [
            { label: 'High', value: 'high' },
            { label: 'Medium', value: 'medium' },
            { label: 'Low', value: 'low' },
          ],
          admin: { width: '25%' },
        },
        {
          name: 'identifiersSource',
          type: 'text',
          admin: { width: '25%' },
        },
        {
          name: 'identifiersVerifiedAt',
          type: 'date',
          admin: { width: '25%' },
        },
      ],
    },
    {
      name: 'careerTrajectory',
      type: 'textarea',
      admin: {
        description: 'Where they went next. Shown once their time with the group is complete.',
        // Was `role === 'alumni'`. Role is the degree and membershipStatus is
        // whether they are still here, so keying this on the role hid the field
        // from all 58 people who had actually left.
        condition: (data) => data?.membershipStatus === 'completed',
      },
    },
  ],
}
