/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    members: Member;
    publications: Publication;
    'research-themes': ResearchTheme;
    projects: Project;
    software: Software;
    'thesis-topics': ThesisTopic;
    news: News;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    members: MembersSelect<false> | MembersSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'research-themes': ResearchThemesSelect<false> | ResearchThemesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    software: SoftwareSelect<false> | SoftwareSelect<true>;
    'thesis-topics': ThesisTopicsSelect<false> | ThesisTopicsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  /**
   * URL-идентификатор; создаётся автоматически, можно поправить вручную
   */
  slug?: string | null;
  /**
   * Аккаунт для self-edit профиля
   */
  user?: (number | null) | User;
  role: 'faculty' | 'researcher' | 'phd' | 'msc' | 'alumni';
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * AI-черновик био. Генерируется пайплайном; владелец профиля переносит нужное в bio.
   */
  bioAiDraft?: string | null;
  researchInterests?: string[] | null;
  orcid?: string | null;
  openalexId?: string | null;
  dblpKey?: string | null;
  links?: {
    /**
     * LinkedIn или страница Técnico — по ТЗ обязательно
     */
    linkedin?: string | null;
    tecnicoPage?: string | null;
    personalPage?: string | null;
    googleScholar?: string | null;
    github?: string | null;
  };
  email?: string | null;
  /**
   * Показывать email на сайте (согласие владельца)
   */
  showEmail?: boolean | null;
  /**
   * Карьерная траектория (для alumni)
   */
  careerTrajectory?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'member';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  /**
   * URL-идентификатор; создаётся автоматически, можно поправить вручную
   */
  slug?: string | null;
  year: number;
  type: 'journal' | 'conference' | 'workshop' | 'book' | 'preprint' | 'other';
  venue?: string | null;
  authors?:
    | {
        name: string;
        member?: (number | null) | Member;
        id?: string | null;
      }[]
    | null;
  abstract?: string | null;
  doi?: string | null;
  openalexId?: string | null;
  pdfUrl?: string | null;
  citationCount?: number | null;
  referencedWorks?: string[] | null;
  /**
   * Проверено человеком (авторство/метаданные корректны)
   */
  verified?: boolean | null;
  /**
   * AI-саммари; после ручной правки поставьте статус edited
   */
  aiSummary?: {
    tldr?: string | null;
    problem?: string | null;
    method?: string | null;
    results?: string | null;
    takeaways?: string | null;
    /**
     * Нетехническое описание для индустрии
     */
    industry?: string | null;
    /**
     * Импакт-нарратив: значимость, применения
     */
    impact?: string | null;
  };
  aiSummaryStatus?: ('none' | 'generated' | 'edited') | null;
  /**
   * Готовый текст поста для LinkedIn/X (генерируется по запросу)
   */
  socialSnippet?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-themes".
 */
export interface ResearchTheme {
  id: number;
  name: string;
  /**
   * URL-идентификатор; создаётся автоматически, можно поправить вручную
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  members?: (number | Member)[] | null;
  keyPublications?: (number | Publication)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL-идентификатор; создаётся автоматически, можно поправить вручную
   */
  slug?: string | null;
  kind?: ('national' | 'international' | 'industry') | null;
  yearStart?: number | null;
  yearEnd?: number | null;
  /**
   * Источник финансирования / грант
   */
  funding?: string | null;
  url?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  members?: (number | Member)[] | null;
  themes?: (number | ResearchTheme)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software".
 */
export interface Software {
  id: number;
  name: string;
  /**
   * URL-идентификатор; создаётся автоматически, можно поправить вручную
   */
  slug?: string | null;
  kind: 'software' | 'dataset';
  description?: string | null;
  /**
   * GitHub / Zenodo / …
   */
  repoUrl?: string | null;
  publications?: (number | Publication)[] | null;
  members?: (number | Member)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thesis-topics".
 */
export interface ThesisTopic {
  id: number;
  title: string;
  /**
   * URL-идентификатор; создаётся автоматически, можно поправить вручную
   */
  slug?: string | null;
  level: 'msc' | 'phd';
  status: 'open' | 'assigned' | 'completed';
  advisors?: (number | Member)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  themes?: (number | ResearchTheme)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL-идентификатор; создаётся автоматически, можно поправить вручную
   */
  slug?: string | null;
  date: string;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedPublications?: (number | Publication)[] | null;
  /**
   * Готовый текст поста для LinkedIn/X (генерируется по запросу)
   */
  socialSnippet?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'research-themes';
        value: number | ResearchTheme;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'software';
        value: number | Software;
      } | null)
    | ({
        relationTo: 'thesis-topics';
        value: number | ThesisTopic;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  user?: T;
  role?: T;
  photo?: T;
  bio?: T;
  bioAiDraft?: T;
  researchInterests?: T;
  orcid?: T;
  openalexId?: T;
  dblpKey?: T;
  links?:
    | T
    | {
        linkedin?: T;
        tecnicoPage?: T;
        personalPage?: T;
        googleScholar?: T;
        github?: T;
      };
  email?: T;
  showEmail?: T;
  careerTrajectory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  type?: T;
  venue?: T;
  authors?:
    | T
    | {
        name?: T;
        member?: T;
        id?: T;
      };
  abstract?: T;
  doi?: T;
  openalexId?: T;
  pdfUrl?: T;
  citationCount?: T;
  referencedWorks?: T;
  verified?: T;
  aiSummary?:
    | T
    | {
        tldr?: T;
        problem?: T;
        method?: T;
        results?: T;
        takeaways?: T;
        industry?: T;
        impact?: T;
      };
  aiSummaryStatus?: T;
  socialSnippet?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-themes_select".
 */
export interface ResearchThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  members?: T;
  keyPublications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  yearStart?: T;
  yearEnd?: T;
  funding?: T;
  url?: T;
  description?: T;
  members?: T;
  themes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software_select".
 */
export interface SoftwareSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  description?: T;
  repoUrl?: T;
  publications?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thesis-topics_select".
 */
export interface ThesisTopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  level?: T;
  status?: T;
  advisors?: T;
  description?: T;
  themes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  coverImage?: T;
  body?: T;
  relatedPublications?: T;
  socialSnippet?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}