/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    members: Member;
    publications: Publication;
    'research-themes': ResearchTheme;
    projects: Project;
    software: Software;
    'thesis-topics': ThesisTopic;
    news: News;
    events: Event;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    members: MembersSelect<false> | MembersSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'research-themes': ResearchThemesSelect<false> | ResearchThemesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    software: SoftwareSelect<false> | SoftwareSelect<true>;
    'thesis-topics': ThesisTopicsSelect<false> | ThesisTopicsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'ai-settings': AiSetting;
  };
  globalsSelect: {
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  /**
   * URL identifier; created automatically, can be edited by hand
   */
  slug?: string | null;
  /**
   * Account for profile self-editing
   */
  user?: (number | null) | User;
  role: 'faculty' | 'researcher' | 'phd' | 'msc' | 'alumni';
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * AI bio draft. Generated by the pipeline; the profile owner moves what they want into bio.
   */
  bioAiDraft?: string | null;
  researchInterests?: string[] | null;
  orcid?: string | null;
  cienciaId?: string | null;
  openalexId?: string | null;
  dblpKey?: string | null;
  tecnicoId?: string | null;
  links?: {
    /**
     * LinkedIn or Técnico page — required by the brief
     */
    linkedin?: string | null;
    tecnicoPage?: string | null;
    personalPage?: string | null;
    googleScholar?: string | null;
    github?: string | null;
  };
  email?: string | null;
  /**
   * Show the email on the site.
   */
  showEmail?: boolean | null;
  /**
   * Show LinkedIn on the public profile.
   */
  showLinkedIn?: boolean | null;
  /**
   * Show GitHub on the public profile.
   */
  showGitHub?: boolean | null;
  /**
   * Show ORCID on the public profile.
   */
  showORCID?: boolean | null;
  /**
   * Show Ciência Vitae on the public profile.
   */
  showCienciaId?: boolean | null;
  /**
   * Show DBLP on the public profile.
   */
  showDBLP?: boolean | null;
  /**
   * Show Técnico page when explicitly stored.
   */
  showTecnicoPage?: boolean | null;
  /**
   * Show personal website on the public profile.
   */
  showPersonalPage?: boolean | null;
  /**
   * Show Google Scholar on the public profile.
   */
  showGoogleScholar?: boolean | null;
  /**
   * Internal provenance for imported contact data. Not rendered publicly.
   */
  contactsSource?: string | null;
  /**
   * When contact data was imported or last reviewed.
   */
  contactsVerifiedAt?: string | null;
  identifiersVerified?: boolean | null;
  identifiersConfidence?: ('high' | 'medium' | 'low') | null;
  identifiersSource?: string | null;
  identifiersVerifiedAt?: string | null;
  /**
   * Career trajectory (for alumni)
   */
  careerTrajectory?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'member';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  /**
   * URL identifier; created automatically, can be edited by hand
   */
  slug?: string | null;
  year: number;
  type: 'journal' | 'conference' | 'workshop' | 'book' | 'preprint' | 'other';
  venue?: string | null;
  authors?:
    | {
        name: string;
        member?: (number | null) | Member;
        id?: string | null;
      }[]
    | null;
  abstract?: string | null;
  doi?: string | null;
  openalexId?: string | null;
  /**
   * Link to the original publication (arXiv / journal / DOI page)
   */
  originalUrl?: string | null;
  pdfUrl?: string | null;
  citationCount?: number | null;
  /**
   * Code, documents, images, datasets or links for this publication
   */
  attachments?:
    | {
        label: string;
        kind: 'code' | 'document' | 'image' | 'dataset' | 'file' | 'link';
        /**
         * Upload a file, or leave empty and use an external URL below
         */
        file?: (number | null) | Media;
        /**
         * External URL (e.g. GitHub repo) — used when no file is uploaded
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  referencedWorks?: string[] | null;
  /**
   * Verified by a human (authorship/metadata are correct)
   */
  verified?: boolean | null;
  /**
   * Editorial state. Only "Published" is visible on the public site.
   */
  status: 'imported' | 'pending_review' | 'approved' | 'published' | 'rejected' | 'failed';
  /**
   * Last reviewer (set automatically on status change).
   */
  reviewer?: (number | null) | User;
  /**
   * Reason for the current decision (e.g. why rejected). Recorded in history.
   */
  reviewNote?: string | null;
  /**
   * Automatic audit trail of editorial decisions.
   */
  reviewHistory?:
    | {
        status?: string | null;
        note?: string | null;
        reviewer?: string | null;
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * AI summary; after editing by hand, set the status to edited
   */
  aiSummary?: {
    tldr?: string | null;
    problem?: string | null;
    method?: string | null;
    results?: string | null;
    /**
     * Main contributions supported by the source abstract
     */
    contributions?: string | null;
    /**
     * Known limitations stated or implied by the source abstract
     */
    limitations?: string | null;
    takeaways?: string | null;
    /**
     * Concrete applications supported by the source abstract
     */
    applications?: string | null;
    /**
     * Research topics or keywords supported by title and abstract
     */
    topics?: string | null;
    /**
     * Non-technical description for industry
     */
    industry?: string | null;
    /**
     * Impact narrative: significance, applications
     */
    impact?: string | null;
  };
  aiSummaryStatus?: ('none' | 'generated' | 'edited') | null;
  aiSummaryModel?: string | null;
  aiSummaryPromptVersion?: string | null;
  aiSummaryGeneratedAt?: string | null;
  /**
   * Ready-to-post text for LinkedIn/X (generated on demand)
   */
  socialSnippet?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-themes".
 */
export interface ResearchTheme {
  id: number;
  name: string;
  /**
   * URL identifier; created automatically, can be edited by hand
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  members?: (number | Member)[] | null;
  keyPublications?: (number | Publication)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL identifier; created automatically, can be edited by hand
   */
  slug?: string | null;
  kind?: ('national' | 'international' | 'industry') | null;
  yearStart?: number | null;
  yearEnd?: number | null;
  /**
   * Funding source / grant
   */
  funding?: string | null;
  url?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  members?: (number | Member)[] | null;
  themes?: (number | ResearchTheme)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software".
 */
export interface Software {
  id: number;
  name: string;
  /**
   * URL identifier; created automatically, can be edited by hand
   */
  slug?: string | null;
  kind: 'software' | 'dataset';
  description?: string | null;
  /**
   * GitHub / Zenodo / …
   */
  repoUrl?: string | null;
  publications?: (number | Publication)[] | null;
  members?: (number | Member)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thesis-topics".
 */
export interface ThesisTopic {
  id: number;
  title: string;
  /**
   * URL identifier; created automatically, can be edited by hand
   */
  slug?: string | null;
  level: 'msc' | 'phd';
  status: 'open' | 'assigned' | 'completed';
  advisors?: (number | Member)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  themes?: (number | ResearchTheme)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL identifier; created automatically, can be edited by hand
   */
  slug?: string | null;
  date: string;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedPublications?: (number | Publication)[] | null;
  /**
   * Ready-to-post text for LinkedIn/X (generated on demand)
   */
  socialSnippet?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL identifier; created automatically, can be edited by hand
   */
  slug?: string | null;
  date: string;
  location?: string | null;
  /**
   * Speaker / organiser (optional)
   */
  speaker?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * External link (registration, recording…)
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'research-themes';
        value: number | ResearchTheme;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'software';
        value: number | Software;
      } | null)
    | ({
        relationTo: 'thesis-topics';
        value: number | ThesisTopic;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  user?: T;
  role?: T;
  photo?: T;
  bio?: T;
  bioAiDraft?: T;
  researchInterests?: T;
  orcid?: T;
  cienciaId?: T;
  openalexId?: T;
  dblpKey?: T;
  tecnicoId?: T;
  links?:
    | T
    | {
        linkedin?: T;
        tecnicoPage?: T;
        personalPage?: T;
        googleScholar?: T;
        github?: T;
      };
  email?: T;
  showEmail?: T;
  showLinkedIn?: T;
  showGitHub?: T;
  showORCID?: T;
  showCienciaId?: T;
  showDBLP?: T;
  showTecnicoPage?: T;
  showPersonalPage?: T;
  showGoogleScholar?: T;
  contactsSource?: T;
  contactsVerifiedAt?: T;
  identifiersVerified?: T;
  identifiersConfidence?: T;
  identifiersSource?: T;
  identifiersVerifiedAt?: T;
  careerTrajectory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  type?: T;
  venue?: T;
  authors?:
    | T
    | {
        name?: T;
        member?: T;
        id?: T;
      };
  abstract?: T;
  doi?: T;
  openalexId?: T;
  originalUrl?: T;
  pdfUrl?: T;
  citationCount?: T;
  attachments?:
    | T
    | {
        label?: T;
        kind?: T;
        file?: T;
        url?: T;
        id?: T;
      };
  referencedWorks?: T;
  verified?: T;
  status?: T;
  reviewer?: T;
  reviewNote?: T;
  reviewHistory?:
    | T
    | {
        status?: T;
        note?: T;
        reviewer?: T;
        at?: T;
        id?: T;
      };
  aiSummary?:
    | T
    | {
        tldr?: T;
        problem?: T;
        method?: T;
        results?: T;
        contributions?: T;
        limitations?: T;
        takeaways?: T;
        applications?: T;
        topics?: T;
        industry?: T;
        impact?: T;
      };
  aiSummaryStatus?: T;
  aiSummaryModel?: T;
  aiSummaryPromptVersion?: T;
  aiSummaryGeneratedAt?: T;
  socialSnippet?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-themes_select".
 */
export interface ResearchThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  members?: T;
  keyPublications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  yearStart?: T;
  yearEnd?: T;
  funding?: T;
  url?: T;
  description?: T;
  members?: T;
  themes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software_select".
 */
export interface SoftwareSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  description?: T;
  repoUrl?: T;
  publications?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thesis-topics_select".
 */
export interface ThesisTopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  level?: T;
  status?: T;
  advisors?: T;
  description?: T;
  themes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  coverImage?: T;
  body?: T;
  relatedPublications?: T;
  socialSnippet?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  location?: T;
  speaker?: T;
  description?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: number;
  /**
   * Model used by all AI features (summaries, chat, snippets). The provider API key must be set in the AI service .env (GROQ_API_KEY, GEMINI_API_KEY, …).
   */
  llmModel?:
    | (
        | ''
        | 'groq/llama-3.3-70b-versatile'
        | 'groq/llama-3.1-8b-instant'
        | 'gemini/gemini-flash-lite-latest'
        | 'gemini/gemini-flash-latest'
        | 'mistral/mistral-small-latest'
        | 'cerebras/gpt-oss-120b'
      )
    | null;
  /**
   * Optional. Any LiteLLM model id (provider/model), overrides the dropdown. Example: ollama/llama3.1
   */
  customModel?: string | null;
  /**
   * Enable or disable AI features site-wide.
   */
  features?: {
    /**
     * Show the RAG chatbot on public pages.
     */
    enableChatbot?: boolean | null;
    /**
     * Use embeddings in search. Off = keyword search only.
     */
    enableSemanticSearch?: boolean | null;
    /**
     * Auto-generate AI summaries when a publication is saved.
     */
    enableSummaries?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  llmModel?: T;
  customModel?: T;
  features?:
    | T
    | {
        enableChatbot?: T;
        enableSemanticSearch?: T;
        enableSummaries?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}